apiVersion: v1
data:
  password: TEF3R1R6Q2VibmVyNEt2ZDIzVU1HRU9Gb0dBZ0VIWURzenJzU1BmQXA2bENXMTVTNGZidnJWcnViV3N1YTlQSQ==
kind: Secret
metadata:
  labels:
    app: gitlab
    release: gitlab
  name: gitlab-gitlab-initial-root-password
  namespace: gitlab
type: Opaque
