apiVersion: v1
data:
  runner-registration-token: TEVqSVVBUm0wMTVwTlc0dXYwbFhqeGpZQ0xxMEZCenNYYmRwemd3SnhNTXY5Z1lUdmJQQVZWU2g1WEFjWGg2WA==
  runner-token: ""
kind: Secret
metadata:
  labels:
    app: gitlab
    release: gitlab
  name: gitlab-gitlab-runner-secret
  namespace: gitlab
type: Opaque
